# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test():
    client = WindmillTestClient(__name__)

    client.open(url=u'http://qacosmo.osafoundation.org/cosmo/browse/%random%')
    client.wait(milliseconds=2000)
    client.reWriteAlert()
    client.click(link=u'[browse]')
    client.wait(milliseconds=2000)
    client.click(link=u'Log Out')
    client.wait(milliseconds=2000)
    client.type(text=u'root', id=u'loginDialogUsernameInput')
    client.type(text=u'cosmo', id=u'loginDialogPasswordInput')
    client.click(id=u'loginSubmitButton')
    client.wait(milliseconds=5000)
    client.click(link=u'Users')
    client.wait(milliseconds=5000)
    client.click(link=u'Log Out')